"""add Tag_count

Revision ID: 2f333cc5f68
Revises: None
Create Date: 2015-09-13 12:48:53.553220

"""

# revision identifiers, used by Alembic.
revision = '2f333cc5f68'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post_Tages',
    sa.Column('Post_id', sa.Integer(), nullable=True),
    sa.Column('Tage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['Tage_id'], ['tags.id'], )
    )
    op.drop_table('post_tages')
    op.add_column('tags', sa.Column('count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'count')
    op.create_table('post_tages',
    sa.Column('Post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Tage_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Post_id'], ['posts.id'], name='post_tages_ibfk_1'),
    sa.ForeignKeyConstraint(['Tage_id'], ['tags.id'], name='post_tages_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Post_Tages')
    ### end Alembic commands ###
