"""inital migration

Revision ID: e652c24484
Revises: None
Create Date: 2015-09-01 15:37:44.229186

"""

# revision identifiers, used by Alembic.
revision = 'e652c24484'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
