"""add body_html

Revision ID: f9be3d3b42
Revises: e652c24484
Create Date: 2015-09-04 15:25:56.745927

"""

# revision identifiers, used by Alembic.
revision = 'f9be3d3b42'
down_revision = 'e652c24484'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
